# Generated by Django 6.0.1 on 2026-01-19 06:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('general', 'General Election'), ('by_election', 'By-Election'), ('referendum', 'Referendum')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, help_text='Official source for this election data')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('registered_voters', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='elections.constituency')),
            ],
            options={
                'ordering': ['constituency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('national', 'National'), ('county', 'County'), ('constituency', 'Constituency'), ('ward', 'Ward')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'name'],
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('manifesto_url', models.URLField(blank=True)),
                ('is_independent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, help_text='Official source for candidate information')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_created', to=settings.AUTH_USER_MODEL)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.position')),
            ],
            options={
                'ordering': ['election', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('verified', models.BooleanField(default=False, help_text='Whether this result has been officially verified')),
                ('source_url', models.URLField(blank=True, help_text='Official source for this result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_created', to=settings.AUTH_USER_MODEL)),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.pollingstation')),
            ],
            options={
                'ordering': ['-votes'],
            },
        ),
        migrations.CreateModel(
            name='VoterEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('voting_process', 'Voting Process'), ('candidates', 'Candidates'), ('positions', 'Positions'), ('timeline', 'Timeline'), ('general', 'General Information')], max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter_education_created', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter_education', to='elections.election')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['date', 'type'], name='elections_e_date_d41ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['is_active'], name='elections_e_is_acti_a71fff_idx'),
        ),
        migrations.AddIndex(
            model_name='pollingstation',
            index=models.Index(fields=['constituency'], name='elections_p_constit_8bebdd_idx'),
        ),
        migrations.AddIndex(
            model_name='pollingstation',
            index=models.Index(fields=['code'], name='elections_p_code_bb6d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'position'], name='elections_c_electio_f79313_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['party'], name='elections_c_party_55172e_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['candidate', 'polling_station'], name='elections_r_candida_e7b775_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['verified'], name='elections_r_verifie_ae3ad1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('candidate', 'polling_station')},
        ),
        migrations.AddIndex(
            model_name='votereducation',
            index=models.Index(fields=['category', 'is_published'], name='elections_v_categor_3e0477_idx'),
        ),
    ]
