# Generated by Django 6.0.1 on 2026-01-19 06:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('violence', 'Violence or Intimidation'), ('irregularity', 'Electoral Irregularity'), ('disruption', 'Disruption or Interference'), ('technical', 'Technical Issue (Power/Communication)'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_description', models.CharField(blank=True, max_length=500)),
                ('photo_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('unverified', 'Unverified'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('responded_to', models.BooleanField(default=False)),
                ('response_notes', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=True, help_text='Anonymous reporting protects citizen privacy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='elections.election')),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='elections.pollingstation')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_incidents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollingStationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('opening', 'Station Opening'), ('closing', 'Station Closing'), ('turnout', 'Voter Turnout'), ('queue', 'Queue Status'), ('general', 'General Update')], max_length=20)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('estimated_turnout', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('queue_wait_time', models.IntegerField(blank=True, help_text='Wait time in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('queue_length', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status_notes', models.TextField(blank=True, help_text='Additional notes about the polling station')),
                ('photo_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('unverified', 'Unverified'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_updates', to='elections.election')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='elections.pollingstation')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_updates', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified_observer', models.BooleanField(default=False, help_text='Accredited observer/CSO')),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('update', 'Polling Station Update'), ('incident', 'Incident Report'), ('result', 'Election Result')], max_length=20)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('disputed', 'Disputed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.pollingstationupdate')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.incidentreport')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.result')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['election', 'incident_type'], name='elections_i_electio_1dd7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['verification_status'], name='elections_i_verific_e2ad4d_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['severity'], name='elections_i_severit_00758b_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['created_at'], name='elections_i_created_23c332_idx'),
        ),
        migrations.AddIndex(
            model_name='pollingstationupdate',
            index=models.Index(fields=['polling_station', 'election'], name='elections_p_polling_66529c_idx'),
        ),
        migrations.AddIndex(
            model_name='pollingstationupdate',
            index=models.Index(fields=['verification_status'], name='elections_p_verific_19da12_idx'),
        ),
        migrations.AddIndex(
            model_name='pollingstationupdate',
            index=models.Index(fields=['created_at'], name='elections_p_created_26f6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='pollingstationupdate',
            index=models.Index(fields=['update_type'], name='elections_p_update__29d766_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone_number'], name='elections_u_phone_n_66d795_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone_verified'], name='elections_u_phone_v_91ca21_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['verification_type', 'status'], name='elections_v_verific_aebdea_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['verified_by'], name='elections_v_verifie_e76fa3_idx'),
        ),
    ]
