# Generated by Django 6.0.1 on 2026-01-19 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_incidentreport_pollingstationupdate_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stream_key', models.CharField(max_length=100, unique=True)),
                ('stream_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio Only')], default='video', max_length=20)),
                ('rtmp_url', models.URLField(blank=True, help_text='RTMP ingest URL')),
                ('hls_url', models.URLField(blank=True, help_text='HLS playback URL')),
                ('webrtc_url', models.URLField(blank=True, help_text='WebRTC URL for low-latency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('paused', 'Paused'), ('ended', 'Ended')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('viewer_count', models.IntegerField(default=0)),
                ('peak_viewers', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_description', models.CharField(blank=True, max_length=500)),
                ('is_recorded', models.BooleanField(default=True)),
                ('recording_url', models.URLField(blank=True, help_text='URL to recorded stream')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_streams', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='elections.election')),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='elections.pollingstation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='elections_l_status_862094_idx'), models.Index(fields=['stream_key'], name='elections_l_stream__651fbd_idx'), models.Index(fields=['election', 'status'], name='elections_l_electio_ff2a0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('live_video', 'Live Video Stream'), ('live_audio', 'Live Audio Stream')], max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('live', 'Live Streaming'), ('ended', 'Stream Ended')], default='uploading', max_length=20)),
                ('external_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds for video/audio', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('stream_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stream_url', models.URLField(blank=True, help_text='HLS/RTMP stream URL')),
                ('live_started_at', models.DateTimeField(blank=True, null=True)),
                ('live_ended_at', models.DateTimeField(blank=True, null=True)),
                ('viewer_count', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(blank=True, help_text='When the media was captured', null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_moderated', models.BooleanField(default=False)),
                ('moderation_notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('incident_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='elections.incidentreport')),
                ('polling_station_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='elections.pollingstationupdate')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['media_type', 'status'], name='elections_m_media_t_1a03fc_idx'), models.Index(fields=['uploaded_by'], name='elections_m_uploade_95fe1d_idx'), models.Index(fields=['created_at'], name='elections_m_created_acd366_idx'), models.Index(fields=['stream_key'], name='elections_m_stream__dcd8c2_idx')],
            },
        ),
    ]
